from turtle import Turtle , Screen
# create a new function
my_turtle = Turtle()
my_turtle.color("red")
my_turtle.forward(10)
my_turtle.penup()
my_turtle.forward(10)
my_turtle.pendown()
my_turtle.forward(10)
my_turtle.penup()
my_turtle.forward(10)
my_turtle.pendown()
my_turtle.forward(10)
my_turtle.penup()
my_turtle.forward(10)
my_turtle.pendown()
my_turtle.forward(10)
my_turtle.penup()
my_turtle.forward(10)
my_turtle.pendown()
my_turtle.forward(10)
my_turtle.penup()
my_turtle.forward(10)
my_turtle.pendown()
my_turtle.forward(10)
my_turtle.penup()
my_turtle.forward(10)
my_turtle.pendown()
my_turtle.forward(10)
my_turtle.penup()
my_turtle.forward(10)
my_turtle.pendown()
my_turtle.forward(10)
my_turtle.penup()
my_turtle.forward(10)
my_turtle.pendown()
my_turtle.forward(10)
my_turtle.penup()
my_turtle.forward(10)
my_turtle.pendown()
my_turtle.forward(10)
my_turtle.penup()
my_turtle.forward(10)
my_turtle.pendown()

my_turtle.shape("turtle")
my_turtle.color("red")


my_screen = Screen()
my_screen.exitonclick()